#! /usr/bin/env python3

from glob import glob
from os import remove
from os.path import expanduser, getmtime, isfile
from sys import exit
from twitter import Api

config_error = '''
Error while reading ".pic2tweet" configuration file. Make sure the file exists following the example below:

[twitter]
api_key = Q2jEkfuGcdN7KwHYNN7Jvje1Q
api_secret = Oph5PVWz62TGTQzpjmG3ou6mtz5boPhVueRmKulPKMfn18EzoC 
access_token = 1277898941226571943-B863QGvWamKz4Ns0yheZ0iAUNs9rMO
access_token_secret = 62zas9Sbqq5pHnVMKUs1feviNSRsAJqd0g3zgxi7mmElF
'''

def twitter_config():
    from configparser import ConfigParser

    config = ConfigParser()
    config.read('.pic2tweet') or config.read(expanduser('~/.pic2tweet'))

    try:
        twitter_config = config['twitter']

        return (
            twitter_config['api_key'],
            twitter_config['api_secret'],
            twitter_config['access_token'],
            twitter_config['access_token_secret']
        )

    except:
        print(config_error)
        exit(1)

def usage():
    print('Usage:')
    print('pic2tweet [api key] [api secret key] [access token] [access token secret]')

def posting(status):
    print(f'Posting {status}...', end='', flush=True)

def posted(status):
    print(f'\rPosted  {status}.  ')

def list_files():
    found = glob('*.jpg') + glob('*.jpeg') + glob('*.gif') + glob('*.png')

    files = list(filter(isfile, found))

    if not files:
        print('No .jpg, .jpeg, .gif or .png files found.')
        exit()

    files.sort(key=getmtime)

    return files

if __name__ == "__main__":
    api = Api(*twitter_config())

    for f in list_files():
        posting(f)
        api.PostUpdate('', f)
        posted(f)
        remove(f)
